### ISSUE TITLE
No warning on importing something that doesn't exist from a file which does

### ISSUE THREAD

**Issue by hollinsky** [atopile/atopile#122]
For instance, if I `import SPi from "generics/interfaces.ato"` with a typo in SPI, it will not fail until later when I try to use the import. Since it does not point to the import, it can take a minute to notice that the import is incorrect.

**Comment by mawildoer** [comment]
It's a good suggestion, and, you're right, it's improve the error clarity there a lot.

I'm not immediately sure how to implement it though. I'll leave it open to think about for a bit.

Thanks for the ping!
