### ISSUE TITLE
`ato install --jlcpcb` error is confusing in case the component doesn't have a footprint

### ISSUE THREAD

**Issue by mawildoer** [atopile/atopile#127]
<img width="733" alt="Screenshot 2024-02-09 at 10 07 15" src="https://github.com/atopile/atopile/assets/4241578/ca5225f1-bd4d-4005-80f3-8b5a0817c381">

**Comment by napowderly** [comment]
Updated error message and added a link to the JLC page
<img width="1140" alt="Screenshot 2024-02-28 at 9 59 22 AM" src="https://github.com/atopile/atopile/assets/8122613/dd6435f9-dc31-4e12-9bb0-173bb4c0ff50">
