### ISSUE TITLE
Publish VSCode extension on Open VSX

### ISSUE THREAD

**Issue by Polsaker** [atopile/atopile#139]
Some linux distros default to using this store instead of Microsoft's. See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by mawildoer** [comment]
Thanks for bringing this up!
How painful is it to install from the Microsoft store for people on these distros? It kinda seems odd that it wouldn't provide compatibility for the regular, defacto store

**Comment by Polsaker** [comment]
According to the [Arch wiki](https://wiki.archlinux.org/title/Visual_Studio_Code#Extensions_support), the easiest way is to download the file from the Microsoft store and install it manually. You won't get updates this way (gotta re-install using the same method each time a new version is published).

I just tried this and had to go to https://marketplace.visualstudio.com/items?itemName=atopile.atopile, version history tab and download the latest file from there

**Comment by mawildoer** [comment]
I see. Alright, I'll see what's involved in getting it posted there

**Comment by mawildoer** [comment]
Done: https://open-vsx.org/extension/atopile/atopile
