### ISSUE TITLE
net namer never adds a prefix for conflicts

### ISSUE THREAD

**Issue by jarrod89** [atopile/atopile#179]
In here bugs lie: https://github.com/atopile/atopile/blob/7abd489a2582768b15de88055934fe8dfbb5d8d2/src/atopile/nets.py#L133
Noticed by many, here is an example: https://discord.com/channels/1022538123915300865/1132741442813562981/1210558850747342868

**Comment by Timot05** [comment]
@jarrod89 do you want to see if this improves it? https://github.com/atopile/atopile/pull/194
