### ISSUE TITLE
Bad escaping of `settings.json` on Windows

### ISSUE THREAD

**Issue by mawildoer** [atopile/atopile#211]
Small thing to fix, when creating a new project, the python.defaultInterpreterPath config in settings.json isn't escaped. 

When an extension tries to read or edit it, it fails because of the formatting errors. 

It wants it to be `"python.defaultInterpreterPath": "C:\\Users\\justi\\Documents\\ato\\venv\\Scripts\\python.exe"`

![image](https://github.com/atopile/atopile/assets/4241578/2fbff887-3f42-4c8d-aee0-90cbdd0bdc7f)

**Comment by justind000** [comment]
Are there any issues with naively replacing `\` with `\\`? 

https://github.com/atopile/atopile/blob/45616aa0217eb45b4a34714d98061eb2ace8de0d/src/atopile/cli/create.py#L317
`"python_path": sys.executable.replace('\\', '\\\\'),`

I don't think there would ever be two backslashes in a valid Windows path, so from a Windows perspective, it seems fine. 
I also don't think there can be backslashes in a *nix/Max path.
