### ISSUE TITLE
Layout reuse breaks with replace operator

### ISSUE THREAD

**Issue by napowderly** [atopile/atopile#237]
Replicating:
Build RP2040 module and use replace operator to add buttons for boot and reset.

Description of issue:
Get a bunch of warnings on build
![Screenshot 2024-03-10 at 11 44 11 AM](https://github.com/atopile/atopile/assets/8122613/26900aef-a018-4e8f-b9b5-bf622a1bf60a)

layout does not link to components properly, only the micro and tracks are grouped

**Comment by mawildoer** [comment]
I left myself this convenient FIXME foreshadowing this exact problem it seems: https://github.com/atopile/atopile/blob/5ff08b701d4f39860c498727fd2b9eddf7c9d2f0/src/atopile/layout.py#L83

Straight forward enough fix!
