### ISSUE TITLE
How make a pcb for a keyboard?

### ISSUE THREAD

**Issue by mamcx** [atopile/atopile#245]
I wish to create a custom keyboard like https://github.com/LouWii/ErgoMax, It will be nice if exists a sample or tutorial to do this kind of project!

**Comment by napowderly** [comment]
Looks cool! Have you checked out some of our getting started videos? Should get you setup with most of the basics, getting parts, making modules etc. Also, feel free to jump on our discord, I am sure you will find people interested in your project!

https://www.youtube.com/watch?v=eMWRwZOajdQ
https://discord.gg/6BEN8bY53G

**Comment by mawildoer** [comment]
@mamcx are these the kind of tutorials you're looking for?

**Comment by mamcx** [comment]
Yeah the tutorial is good. I think I need to consider how adapt it to a keyboard...

**Comment by mawildoer** [comment]
Jump on discord if you’re looking for a hand! https://discord.gg/nkpC7wYRVw
