### ISSUE TITLE
ato install {package} does not add dependency to ato.yaml

### ISSUE THREAD

**Issue by napowderly** [atopile/atopile#262]
When installing to an older project without dependencies, or empty dependencies, causes error and does not add to deps:
![Screenshot 2024-03-20 at 12 47 51 PM](https://github.com/atopile/atopile/assets/8122613/8bacc1be-9562-40f5-ae7c-60308acdee49)
![Screenshot 2024-03-20 at 12 48 24 PM](https://github.com/atopile/atopile/assets/8122613/1ff1645d-c7c3-4114-a91a-4750807fd29c)

**Comment by mawildoer** [comment]
It kind of does, just in this case it's actually missing the `dependencies` key. There's probably a hacky fix for this, but the easiest thing is to include that key just empty as `dependencies: []`

**Comment by napowderly** [comment]
Perhaps a better error message?

**Comment by mawildoer** [comment]
Closing as duplicate
