### ISSUE TITLE
assertions dont work with negative numbers

### ISSUE THREAD

**Issue by napowderly** [atopile/atopile#278]
Want to be able to capture negative voltage/current rating

![Screenshot 2024-04-09 at 10 14 09 AM](https://github.com/atopile/atopile/assets/8122613/ebcf9d21-a845-439b-8a12-a9d812289201)
<img width="689" alt="Screenshot 2024-04-09 at 10 13 56 AM" src="https://github.com/atopile/atopile/assets/8122613/28413315-c9f9-4914-944c-e45eeb673b7d">

**Comment by mawildoer** [comment]
I don't think this is an issue with the asserions, I think it's an issue with the ranged values parsing?
In that it looks like it has parsed the `-400mV to 400mV` as `400mV to 400mV`

**Comment by mawildoer** [comment]
This is the section of the front-end responsible for handling these inversions; https://github.com/atopile/atopile/blob/eb7433b79ee0304cf0333b50719b071680109262/src/atopile/front_end.py#L640-L646
