### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by Marcus10110** [atopile/atopile#414]
The top level "Docs" link on https://atopile.io/ shows a 404 page. It takes you to https://atopile.io/getting-started.md
![image](https://github.com/atopile/atopile/assets/1790201/dbb770ea-72e6-471a-963f-2bae5c5ec0d0)

This might have been broken by this PR: https://github.com/atopile/atopile/pull/412

The rest of the docs page are there, but they are hard to reach. Once you're there, you can see the top doc page, where getting started used to be, now says "None"
https://atopile.io/first_project/

![image](https://github.com/atopile/atopile/assets/1790201/015b03ba-5428-4689-a5c9-a9467effb22c)

**Comment by mawildoer** [comment]
Thanks @Marcus10110 ! Fixed that up
