### ISSUE TITLE
Do Not Populate and Exclude From BOM

### ISSUE THREAD

**Issue by sethfischer** [atopile/atopile#419]
Proposed syntax for implementing "Do Not Populate" and "Exclude From BOM"

The terms "Do Not Populate" and "Exclude From BOM" are borrowed from the [KiCad eeschema options](https://docs.kicad.org/8.0/en/eeschema/eeschema_schematic_creation_and_editing.html#symbol-fields-table).

## Do Not Populate

From the KiCad docs:
> In the BOM, this field resolves to the string "DNP" if the symbol’s DNP attribute is set, or an empty string otherwise.

Indicates that the fab house should not populate a component. But the component should appear in the BOM. This could be used for optional components that may be fitted by the end user.

Possible syntax is setting attribute `do_not_place` (or `dnp`, or `do_not_populate`) to true:

```
component MyComponent:
    do_not_place = true
    lcsc_id = "CXXXX"
    mpn = "CXXXX"
    p1 ~ pin 1
```

## Exclude From BOM

From the KiCad docs:
> Symbol with the exclude from BOM attribute set are not included in the BOM.

Indicates the component should not appear in the BOM (meaning the fab house cannot place the component). This could be used for footprints such as mounting holes and fiducial markers that are defined in ato code but should not be listed in the BOM.

Possible syntax is setting attribute `exclude_from_bom` to true:

```
component MyComponent:
    exclude_from_bom = true
    footprint = "Fiducial:Fiducial_0.75mm_Mask1.5mm"
```

In this case the warning "WARNING No MPN ... has no MPN" would not be issued.

**Comment by mawildoer** [comment]
@sethfischer wanna take the PR for a spin?? `mawildoer/419-do-not-populate`
