### ISSUE TITLE
Error when passing values around with replace operator

### ISSUE THREAD

**Issue by napowderly** [atopile/atopile#457]
I want to be able to specify a load capacitance in a given crystal component definition like so:
<img width="445" alt="Screenshot 2024-08-04 at 5 53 36 PM" src="https://github.com/user-attachments/assets/def9bc18-36f8-4958-ad9c-3206b6be31fe">

Then use that value to pass along to the generic 'oscillator' class to set the cap values
<img width="445" alt="Screenshot 2024-08-04 at 5 53 19 PM" src="https://github.com/user-attachments/assets/770bba3e-8744-4b28-b7bc-2616be66c1ff">

Replacement is done one level up:
<img width="583" alt="Screenshot 2024-08-04 at 5 55 28 PM" src="https://github.com/user-attachments/assets/cde13911-07f0-441e-8b9d-9f820535c635">

Error seems to indicate replacement isnt happening successfully as it claims no MPN or value:
<img width="1529" alt="Screenshot 2024-08-04 at 5 53 05 PM" src="https://github.com/user-attachments/assets/bff99364-0418-4e71-a13a-12bdafa173df">

**Replicate by building swift wing on commit below:**
https://github.com/atopile/swift-wing
commit: bc61bfa4cd4057ff20e84fd057bdf2d97142ea01

**Comment by napowderly** [comment]
Figured it out, I have bad spelling for oscillator. Could use a better error though!

**Comment by mawildoer** [comment]
It should also throw another error for trying to dot-access an object that doesn't exist. No error thrown in the log for the `oscilator.crystal` line?
