### ISSUE TITLE
Reconsider: .vscode in repo

### ISSUE THREAD

**Issue by iopapamanoglou** [atopile/atopile#521]
Pros of .vscode in repo:
- Default settings for new contributors

Cons
- Can't override locally workspace-wide settings (only with `git update-index --skip-worktree`)

**Comment by mawildoer** [comment]
We're note the only ones: https://github.com/microsoft/vscode/issues/40233

This is a potential patch for the moment: https://marketplace.visualstudio.com/items?itemName=swellaby.workspace-config-plus
