### ISSUE TITLE
KiCad plugin: publish on the official kicad plugin repo/installer

### ISSUE THREAD

**Issue by ruben-iteng** [atopile/atopile#657]
### Feature Request

We can commit the atopile-kicad-plugin [here](https://gitlab.com/kicad/addons/metadata).

This would make installing/updating it also very easy (via the build-in plugin manager in KiCad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mawildoer** [comment]
The KiCAD plugin is tightly couple to the atopile version, and reliant upon it, so it can't be installed standalone
