### ISSUE TITLE
Create a public repository for components 

### ISSUE THREAD

**Issue by Xumeiquer** [atopile/atopile#92]
It would be nice to have a component manager similarly to PyPI, NPN, Docker Hub, or Helm among others for electronics components that atopile can use.

This component manager must be capable of dealing this potential dependencies and versions. Maybe a simple `requirements.txt` as Python does will suffice the needs, but it might be interesting to have something more elaborate like `package.json` in npm.

**Comment by mawildoer** [comment]
We do have the most absolutely possible barebones https://packages.atopile.io/, which fills the MVP of the niche.

This week we’re working on a rewrite of it so it doesn’t look and function like it’s straight from 20005 😅

The ato.yaml project definition does also accept dependencies. Are there specific features you’re after?
